# This workflow will build a package using Nuget and then publish it to Github and Nuget.org when a release is created

name: Nuget Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core # required by the `gpr` tool
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    # - name: Setup .NET Core # required by ClientSDK
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: 5.0.100-rc.2.20479.15

    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

#    - name: Test
#      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack --configuration Release --no-restore --include-symbols

    - name: Upload Release Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_name="${GITHUB_REF##*/}"
        hub release edit $(find ./RelationalAI/bin/Release -type f -name "RelationalAI.*.nupkg" -printf "-a %p ") -m "" "$tag_name"

    - name: Install gpr tool
      run: dotnet tool install gpr -g

    - name: Push generated package to GitHub registry
      run: |
        for f in RelationalAI/bin/Release/*.nupkg
        do
          gpr push $f -k ${{ secrets.GITHUB_TOKEN }}
        done
      shell: bash

    # Publish
    - name: Publish Nuget Package to Nuget.org
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: RelationalAI/RelationalAI.csproj

        # NuGet package id, used for version detection & defaults to project name
        # PACKAGE_NAME: RelationalAI

        # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
        # VERSION_FILE_PATH: RelationalAI/RelationalAI.csproj

        # Regex pattern to extract version info in a capturing group
        # VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$

        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: false

        # Format of the git tag, [*] gets replaced with actual version
        # TAG_FORMAT: v*

        # API key to authenticate with NuGet server
        NUGET_KEY: ${{secrets.NUGET_KEY}}

        # NuGet server uri hosting the packages, defaults to https://api.nuget.org
        # NUGET_SOURCE: https://api.nuget.org

        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: true
